server:
  port: 8088

environment:
  application: eksperimentarium-development
  name: dev


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  security:
    oauth2:
      client:
        registration:
          testapp:
            provider: testapp
            client-id: testapp
            client-secret: EttLangtPassord
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          testapp:
            issuer-uri: http://127.0.0.1:5556/dex
