version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2
    steps:
      - checkout
      - run: mkdir -p workspace
      - run: mvn clean install
      - run: pwd
      - run: ls -la
      - run: cp server/target/application.jar workspace/application.jar
      - store_artifacts:
          path: server/target/application.jar
          destination: application.jar
      - persist_to_workspace:
          root: workspace
          paths:
            - application.jar
  docker-image:
    machine: true
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run: pwd
      - run: ls -la
      - run:
          name: docker-image
          command: |
            docker build --build-arg JAR_FILE=workspace/application.jar --tag lovholmacr/test:latest .
orbs:
  azure-acr: circleci/azure-acr@0.1.1
workflows:
  version: 2.1
  build_and_docker-image:
    jobs:
      - build
      - docker-image:
          requires:
            - build
      - azure-acr/build-and-push-image:
          requires:
            - docker-image
