version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2
    steps:
      - checkout
      - run: mvn clean install
      - store_artifacts:
          path: /server/target/application.jar
          destination: application.jar
  docker-image:
    machine: true
    steps:
      - checkout
      - run:
          name: docker-image
          command: |
            docker build --build-arg JAR_FILE=server/target/application.jar --tag olovholm/test:latest .
workflows:
  version: 2
  build_and_docker-image:
    jobs:
      - build
      - docker-image