version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.2
    steps:
      - checkout
      - run: mvn clean install
      - run: docker build-arg JAR_FILE=server/target/application.jar -t olovholm/test