apiVersion: apps/v1
kind: Deployment
metadata:
  name: eksperimentarium
  namespace: prod
  labels:
    app: eksperimentarium
    team: lovholm
spec:
  replicas: 1
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: eksperimentarium
  template:
    metadata:
      labels:
        app: eksperimentarium
    spec:
      containers:
        - name: eksperimentarium
          image: lovholmacr.azurecr.io/eksperimentarium
          ports:
            - containerPort: 80
          env:
            - name: "spring_profiles_active"
              value: "prod"
