apiVersion: v1
kind: Service
metadata:
  name: eksperimentarium-svc
  namespace: prod
  labels:
    app: eksperimentarium
    team: lovholm
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      protocol: TCP
  selector:
    app: eksperimentarium
