apiVersion: v1
kind: Service
metadata:
  name: eksperimentarium-svc
  labels:
    app: eksperimentarium
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      protocol: TCP
  selector:
    app: eksperimentarium
