apiVersion: v1
kind: Service
metadata:
  name: eksperimentarium-service
  labels:
    app: eksperimentarium
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
      protocol: TCP
  selector:
    app: eksperimentarium

---
apiVersion:	apps/v1
kind: Deployment
metadata:
    name: eksperimentarium-deployment
spec:
  replicas: 3
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: eksperimentarium
  template:
    metadata:
      labels:
        app: eksperimentarium
    spec:
      containers:
        - name: eksperimentarium
          image: lovholmacr.azurecr.io/eksperimentarium:0.5-a735f715ec4082264a04d4b9d2e91ecc39970376
          ports:
            - containerPort: 80
              name: server
          env:
            - name: "spring_profiles_active"
              value: "prod"
