apiVersion: v1
kind: Service
metadata:
  name: eksperimentarium
  labels:
    run: eksperimentarium
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      protocol: TCP
  selector:
    run: eksperimentarium

---
apiVersion:	apps/v1
kind: Deployment
metadata:
    name: eksperimentarium
spec:
  replicas: 3
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: eksperimentarium
  template:
    metadata:
      labels:
        app: eksperimentarium
    spec:
      containers:
        - name: eksperimentarium
          image: lovholmacr.azurecr.io/eksperimentarium:latest
          ports:
            - containerPort: 80
