name: Bygg pull request

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build
        shell: bash
        run: |
          echo "Building $(echo $GITHUB_SHA | cut -c1-7)"
          mvn package --batch-mode --file pom.xml -Dchangelist= -Dsha1=-$(git log -1 --pretty='%ad' --date=format:'%Y%m%d%H%M%S')-$(echo $GITHUB_SHA | cut -c1-7)
      - name: Notification til slack
        shell: bash
        run: |
          curl -X POST --data-urlencode \
          "payload={\"channel\": \"#playing-with-tech\", \
          \"username\": \"verdikjedetesteren\", \
          \"blocks\": [ { \"type\": \"section\", \"text\": {  \
          \"type\": \"mrkdwn\",
          \"text\": \"<https://navikt.github.io/k9-verdikjede/|Testrapport> \n :scream: De automatiske testene feilet\"
          } } ], \
          \"icon_emoji\": \":snowman:\"}" ${{ secrets.SLACK_WEBHOOK }}
