name: Send melding til slack ved oppdatering i repo

on:
  registry_package:
    types: [published, updated]

jobs:
  tacotaxi:
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        shell: bash
        run: |
          curl -X POST --data-urlencode \
          "payload={\"channel\": \"#playing-with-tech\", \
          \"username\": \"registrypackagemannen\", \
          \"text\": \"Makotaco, I love you :sunflower:.\", \
          \"icon_emoji\": \":sunglasses:\"}" ${{ secrets.SLACK_WEBHOOK }}
